name: Build tRackIT-OS Images

on: push

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')

  build-tRackIT-OS:
    runs-on: ubuntu-24.04
    needs: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.PAT_JONASHOECHST }}

      - name: Run tRackIT-OS.Pifile
        uses: Nature40/pimod@v0.7.0
        with:
          pifile: tRackIT-OS.Pifile

      - name: Package tRackIT-OS-arm64-${{github.ref_name}}.zip
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mv tRackIT-OS-arm64.img tRackIT-OS-arm64-${{github.ref_name}}.img
          zip tRackIT-OS-arm64-${{github.ref_name}}.zip tRackIT-OS-arm64-${{github.ref_name}}.img

      - name: Upload Release tRackIT-OS-arm64-${{github.ref_name}}.zip
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{github.ref_name}} tRackIT-OS-arm64-${{github.ref_name}}.zip
